### PR TITLE
Fix linux build

### LINKED ISSUE #17: Linux port
The project compiles and runs under linux after some changes and commenting out the audio code. Below is the list of functions and macros that need to be reimplemented for linux:

- [x] `_splitpath`
- [x] `filelength`
- [x] `stricmp` → alias to `strcasecmp`
- [x] `strnicmp`
- [x] `strupr`
- [x] `strlwr`
- [x] `itoa`
- [x] `CopyFileA`
- [x] `timeGetTime`
- [x] `GetTickCount`
- [x] `min` → macro `#define MIN(a, b)  (((a) < (b)) ? (a) : (b))`
- [x] `max` → macro `#define MAX(a, b)  (((a) > (b)) ? (a) : (b))`
- [x] `_MAX_DIR` → ?
- [x] `_MAX_FNAME` → `FILENAME_MAX`
- [x] `_MAX_EXT ` → ?
- [x] `MAX_PATH` → `PATH_MAX` 

Also, what about the mutexes? I don't understand what the autorun.c/h file is for except preventing multiple instances of the game being run.

### PR DESCRIPTION
**Pull request by JanSimek**
Closes #17

### CODE REVIEW

**Comment by alexbatalov** [comment]
I'm still checking this. I was only able to compile it with some cmake changes, using i386 libraries and toolchain.  `compat_timeGetTime` did not work as expected, it stopped all movies once sync was requsted. Using `steady_clock` from `chrono` fixed that. One more issue is `SDL_SetRelativeMouseMode`, mouse does not report any movement at all (at least in VM). Please post your setup, in the meantime I'll try to reproduce build steps in fresh VM to replicate GitHub Actions environment.

Do not remove `WIN32` from `add_executable`. If you do it, MSVC will think it's SUBSYSTEM:CONSOLE and will add blank console window in addition to showing SDL window.

**Comment by JanSimek** [comment]
`E: The repository 'https://adoptopenjdk.jfrog.io/adoptopenjdk/deb jammy Release' does not have a Release file.`

Hmm, I don't understand why the linux build action fails in this pull request while it [succeeds in my fork](https://github.com/JanSimek/fallout2-ce/actions/runs/2419124785).

**Comment by JanSimek** [comment]
OK, it works now. That's how I compile fallout2-ce on linux except I am using Arch.

**Comment by JanSimek** [comment]
I do not experience any mouse issues. The only problem is that when I use fullscreen mode and quit the game then my desktop resolution is not reverted back to normal but stays at 640x480.

**Comment by alexbatalov** [comment]
I guess there is a bug in libsdl dependencies in ubuntu 20.04, and 22.04 is in beta, which can itself be a problem. Other than that, this is terrific news!

**Comment by JanSimek** [comment]
Also, Ubuntu 20 has an older SDL which doesn't have one of the KMOD_'s used in fallout2-ce so it wouldn't compile.

BTW, timeGetTime is still buggy. I didn't commit the fix when you said you'll use chrono

**Comment by JanSimek** [comment]
Sure, there could be an option to choose whether to use system or bundled libraries

**Comment by burner1024** [comment]
Would static build resolve glibc issues though?
20.04: `/fallout2-ce: /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./fallout2-ce)`
Even Ubuntu 18.04 is supported until 2023, and 20.04 goes until 2025.

**Comment by alexbatalov** [comment]
I've tried once again 20.04, it cannot install `libsdl` because of conflicting packages. Some people say it can be fixed by using `aptitude` which is capable of downgrading offending packages. I haven't checked it.

There is no such problem on 18.04, but it complains on `KMOD_SCROLL`, which can be easily checked with `SDL_VERSION_ATLEAST`:
```c
#if SDL_VERSION_ATLEAST(2, 0, 18)
    if ((SDL_GetModState() & KMOD_SCROLL) != 0) {
        gModifierKeysState |= MODIFIER_KEY_STATE_SCROLL_LOCK;
    }
#endif
```

But since we're using `filesystem` it does not compile.

**Comment by burner1024** [comment]
There's no problem in ubuntu, it's a problem in [github image](https://github.com/actions/virtual-environments/issues/4589).
I fixed the package issue, but the build still [fails](https://github.com/BGforgeNet/fallout2-ce/runs/6725270330) on KMOD on 20.04.

**Comment by alexbatalov** [comment]
@burner1024 looks like that [helped](https://github.com/alexbatalov/fallout2-ce/actions/runs/2439328781), build passed with KMOD_SCROLL behind SDL version check. Please check, I will merge into main.

**Comment by burner1024** [comment]
On my machine, it switches resolution, then crashes.
```
[73869.787477] fallout2-ce[57903]: segfault at 0 ip 00000000f78f062a sp 00000000ff9b7564 error 4 in libc-2.31.so[f787b000+15b000]
[73869.787494] Code: 5f c3 66 90 66 90 66 90 66 90 66 90 66 90 66 90 f3 0f 1e fb 56 57 8b 7c 24 0c 31 c0 89 f9 83 e1 3f 66 0f ef c0 83 f9 30 77 17 <f3> 0f 6f 0f 66 0f 74 c1 66 0f d7 d0 85 d2 75 6f 89 f8 83 e0 f0 eb
```

**Pull request merged**
