### PR TITLE
Change the way the touchscreen operates

### PR DESCRIPTION
**Pull request by sonilyan**
Change the way the touchscreen operates - instead of double-tap and triple-tap, use two-handed operation, which is more suitable for mobile phones or tablets.

Clicking the left side of the screen is the right mouse button. Long press and drag are the same as mouse operations.

There is a video as an example：

https://user-images.githubusercontent.com/26177176/196035080-da609d06-6730-4c50-8b67-6af1fb948b1f.mp4

### CODE REVIEW

**Comment by sonilyan** [comment]
update: hold the left side, directly click the UI button to take effect


https://user-images.githubusercontent.com/26177176/196143916-0b5edef1-ee4b-440e-b161-2c8336e8a79b.mp4

**Comment by Janiczek** [comment]
@sonilyan This is unrelated to your actual PR but ... how do you compile fallout2-ce for Android? I've noodled around with Android Studio etc. and needed to patch a lot of the libsdl Java wrappers, and eventually got an `.apk` file out of it, but it didn't run on my phone. What's your process?

**Comment by sonilyan** [comment]
> @sonilyan This is unrelated to your actual PR but ... how do you compile fallout2-ce for Android? I've noodled around with Android Studio etc. and needed to patch a lot of the libsdl Java wrappers, and eventually got an `.apk` file out of it, but it didn't run on my phone. What's your process?

I just use Android Studio open the os/android folder as an project,then [build->refresh linked c++ project]，and [build->make project] -> [make->generate signed apk]...

**Comment by Motherfuckre** [comment]
How to download your build?

**Comment by sonilyan** [comment]
> How to download your build?

I build an apk for you,check it out in my release.

**Comment by sonilyan** [comment]
> How to download your build?

@Motherfuckre I build an apk for you , check it out in my release

**Comment by sonilyan** [comment]
The clickable area of many buttons has been expanded to facilitate clicking, especially for mobile phones, the click operation will become easier.

https://user-images.githubusercontent.com/26177176/201334939-72beb91c-f434-4ec3-ba6b-6d6c42b7ab83.mp4

**Comment by CroTard** [comment]
Your release doesn't work on galaxy tab A8, mouse has to be clicked at least 5-10 times before it registers click, and that button expansion you showed on video also doesn't work. I maybe testing wrong release, it's named Test in your repo.

**Comment by sonilyan** [comment]
> Your release doesn't work on galaxy tab A8, mouse has to be clicked at least 5-10 times before it registers click, and that button expansion you showed on video also doesn't work. I maybe testing wrong release, it's named Test in your repo.

@CroTard I build a new release for you, I've not test it on pad device,Its works fine on my mobile phone.

release name : 2022_12_2

**Comment by CroTard** [comment]
> > Your release doesn't work on galaxy tab A8, mouse has to be clicked at least 5-10 times before it registers click, and that button expansion you showed on video also doesn't work. I maybe testing wrong release, it's named Test in your repo.
> 
> @CroTard I build a new release for you, I've not test it on pad device,Its works fine on my mobile phone.
> 
> release name : 2022_12_2

Still not working, i couldn't upload file directly despite lowering reslotion.. so here is the video 
https://drive.google.com/file/d/1rEDDscBikCGHfm2FuP8bYLbe4yYh8Psy/view?usp=drivesdk

**Comment by CroTard** [comment]
So while holding left side of screen I can click inventory, pipboy etc with my right finger, but i have to click like a madman, like shown in video. So i suspect the only thing not working is actual clicking

**Comment by sonilyan** [comment]
> So while holding left side of screen I can click inventory, pipboy etc with my right finger, but i have to click like a madman, like shown in video. So i suspect the only thing not working is actual clicking

@CroTard I build a new release : [test for touch time](https://github.com/sonilyan/fallout2-ce/releases/tag/2022_12_3)

create ddraw.ini and add this：

[MISC]
TouchCheck=500

if not working, increase the value to test whether it works normally,maybe 800,1000,2000....

**Comment by CroTard** [comment]
> > So while holding left side of screen I can click inventory, pipboy etc with my right finger, but i have to click like a madman, like shown in video. So i suspect the only thing not working is actual clicking
> 
> @CroTard I build a new release : [test for touch time](https://github.com/sonilyan/fallout2-ce/releases/tag/2022_12_3)
> 
> create ddraw.ini and add this：
> 
> [MISC] TouchCheck=500
> 
> if not working, increase the value to test whether it works normally,maybe 800,1000,2000....

Nope, still not working.. I maybe get quicker response but I still have click like crazy to get a click. I tried it on my phone Samsung S20+ and it's the same story so it must be something wrong wrong with code. I'm no good at kotlin smh

**Comment by bruenor41** [comment]
I don't know how to push changes, sorry for putting it here, maybe someone will be interested.
I added changes to zip, it includes compiled apk too : <a href="https://drive.google.com/file/d/1nDgXGBNopQhz_bwK3oPnsUtqs7hzePCI/view?usp=share_link">Download"</a>

Touch controls are:

tap - left click
drag - move
touch down  and hold - left mouse down
first finger down and second finger tap - right click

+ I added buttons for quick access

Screenshot_20230214_110834_Fallout 2 (Debug)

**Pull request closed without merging**
