### PR TITLE
Feature/real time implementation

### PR DESCRIPTION
**Pull request by MakoRehaps**

### CODE REVIEW

**Comment by MakoRehaps** [comment]
sorry misclicked sorry to bother you

**Comment by phobos2077** [comment]
So, you want to turn FO2 into FOnline?

**Comment by MakoRehaps** [comment]
Hey man sorry it was a accident no I wanna play fallout 2 with real time
combat sorry to bother you

**Comment by MakoRehaps** [comment]
It’s a fun thing. For me pretty much

**Comment by MakoRehaps** [comment]
> So, you want to turn FO2 into FOnline?

No no bro I am trying to make realtime fallout 2 no mmo stuff and i wanna try make couch coop realtime fallout 2 lol well cause i wanna play it only reason im doing this

**Comment by MakoRehaps** [comment]
sorry im super new to github sorry to bother you bro

**Pull request closed without merging**
