### PR TITLE
Delete critter from combat during _partyFixMultipleMembers

### PR DESCRIPTION
**Pull request by roginvs**
This PR fixes an issue when we load a game with party member list, then add those critters into AI lists and then unallocate those objects.

Original game works fine but CE was crashing. Now it works.

### CODE REVIEW

**Comment by alexbatalov** [comment]
Do you have a failing save game so I can check why original game works?

**Comment by roginvs** [comment]
I use Fallout: Nevada from Foxx 2.4.1 [https://vk.com/rebuild_by_foxx?w=wall-174451664_4921]. Load this savegame [SLOT10 Battle 1.tar.gz](https://github.com/alexbatalov/fallout2-ce/files/11361621/SLOT10.Battle.1.tar.gz) and attack someone.

`NEVADA_FE.exe` works even without `SFall`

**Comment by alexbatalov** [comment]
I've checked this save, there are no party members, so I cannot reproduce it. Do you have other failing save?

**Comment by roginvs** [comment]
Did you actually tried to run it on Fallout Nevada or just inspected this save file? Here is a screenshot from debugging session. I took fresh install of Naveda from Foxx (link above), compiled fallout2-ce from 2565900f904934a9e0f7f615d3407a1e83783a39 (latest commit on this repository) and made a breakpoint

image

**Comment by alexbatalov** [comment]
This is an interesting case. First of all it does work on 2.0.3.3 (that's why I was not able to replicate it), but it crashes on 2.4.1, because there are changes in `party.txt` (more party members).

The real problem is the function itself, I've incorrectly decompiled in the first place. As you've already noted there is no such bug in the original game.

When an object is deleted, its node is dealloced. Iteration's `gObjectFindLastObjectListNode` becomes a dangling pointer. Which leads to a crash when `objectFindNext` is called. This behaviour is compiler-dependent, that's why simple `_combat_delete_critter` did the trick for you on Linux (I've checked on macOS and it also worked, but crashed on Windows where freed memory is immediately filled with `0xDDDDDDDD`).

`combat_delete_critter` is indeed needed and in fact it is present in other places (primarily in scripting) where we're killing or otherwise destroying critters. `combatai_delete_critter` is called inside `combat_delete_critter` and therefore redundant.

**Comment by roginvs** [comment]
Very good explanation, thanks!

**Pull request merged**
