### PR TITLE
Add StartingMap configuration option from Sfall

### LINKED ISSUE #14: Configurable starting map
Feature proposal to make the starting map configurable. My use case is to launch fallout directly from [my map editor](https://github.com/JanSimek/geck-map-editor). Modders will find this useful for testing their maps without having to recompile fallout2-ce.

Sfall already includes this option:

```ini
[Misc]
;To start a new game somewhere other than artemple.map, uncomment the next line and set it to the map you want to load
;StartingMap=
```

### PR DESCRIPTION
**Pull request by JanSimek**
Closes #14

### CODE REVIEW

**Comment by JanSimek** [comment]
I would also like to make the `isMapper` flag configurable and if it is set then skip main menu and go directly to the map. 

Now that we have C++ support can I add an overload for `configGetString` which would use std::string?

```c++
bool configGetString(Config* config, const char* sectionKey, const char* key, std::string& valueRef);
```

**Comment by JanSimek** [comment]
I found a small bug in this pull request. The StartingMap config entry is saved into fallout2.cfg because it is parsed with `configParseCommandLineArguments`

**Comment by alexbatalov** [comment]
This is expected since command line arguments are shared for both configs. It's not a problem that some new values slips into fallout2.cfg. We'll get rid of it once we migrate to a new unified config, likely fallout2.json.

**Comment by alexbatalov** [comment]
I've traced `isMapper` flag's origin. `mapper2.exe` simply sets it to 1 when calling `gameInitWithOptions`, but uses completely different main loop (`falloutMain`), so it's not configurable in the original game. What's interesting is that there is a global `gIsMapper`, but often code relies on checking `executable` from `gGameConfig` to be `mapper`, so there is no consistency.

**Pull request merged**
